config/routes.rb
HackerNews::Application.routes.draw do
  resources :links 
  resources :votes
  resources :comments

  root to: 'links#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  validates :content, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :votes
  has_many :comments, as: :commentable
  validates :url, :presence => true, :url => true

  def score 
    self.votes.count - (Time.now - self.created_at)/ 3600
  end

  def self.sort_by_score 
    self.all.sort_by {|link| link.score }.reverse
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base 
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:object_type] == "link"
      @comment = Link.find(params[:link_id]).comments.new
    else
      @comment = Comment.find(params[:comment_id]).comments.new
    end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save  
      redirect_to root_url, notice: "Comment successfully added!"
    else
      render :new
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @link = Link.new
    @links = Link.sort_by_score
  end

  def create 
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path, notice: "Link successfully added!"
    else
      render 'index'
    end
  end

private
  def link_params
    params.require(:link).permit(:url)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create 
    @link = Link.find(params[:link_id])
    @link.votes.create
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Write a new comment</h1>

<div id="post-comment" class="row">
  <%= form_for @comment do |f| %>
    <fieldset class="small-12 columns">
      <legend>Post a new comment</legend>
        <%= render 'partials/display_errors', object: f.object %>
      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <%= f.text_field :content, placeholder: "Post your new comment" %>
      <%= f.submit "Post comment" %>
    </fieldset>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Slacker News</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/_display_links.html.erb
<ul class="no-bullet">
  <% @links.each_with_index do |link, index| %>
    <li>
      <%= link_to link.url, link.url %>
      Posted on:
      <%= link.created_at.localtime.strftime("%d %b'%y, %H:%M") %>
      | Votes: <%= link.votes.count %> 
      <%= link_to 'Upvote', votes_path(link_id: link.id), :method => :post, :id =>"link-#{index + 1}"%>
      | <%= link_to 'Comment', new_comment_path(link_id: link.id, :object_type => :link) %>
      | <a class="comments">View comments</a>
      <div class="hidden">
        <%= render 'partials/comments', object: link %>
      </div>
    </li>
  <% end %>
</ul>  

app/views/links/index.html.erb
<div class="row">
  <h1 class="large-5 large-offset-3 small-12 columns">Slacker News</h1>
</div>

<div class="row">
  <%= form_for @link do |f| %>
    <fieldset class="small-12 columns">
      <legend>Post a new link</legend>
        <%= render 'partials/display_errors', object: f.object %>
      <%= f.text_field :url, placeholder: "Post your new link" %>
      <%= f.submit "Submit" %>
    </fieldset>
  <% end %> 
</div>
<section class="links_body">
  <div class="row">
    <% if !@links.nil? %>
      <%= render 'links/display_links' %>
    <% end %>
  </div>
<section>

app/views/partials/_comments.html.erb
<% if object.comments.any? %>
  <ul>
    <% object.comments.each do |comment| %>
      <li>
        <%= comment.content %>
        <%= link_to 'Comment', new_comment_path(:comment_id => comment.id, :object_type => :comment) %>
        <%= render 'partials/comments', object: comment %>
      </li>  
    <% end %>
  </ul>
<% end %>

app/views/partials/_display_errors.html.erb
<% if object.errors.any? %>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>